before_script:
  - bundle install

variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

stages:
  - test
  - build
  - relase

test_project:
  stage: test
  script:
  - bundle exec fastlane test
  tags:
  - Xcode11

build_project:
  stage: build
  script:
  - bundle exec fastlane test
  tags:
  - Xcode11

upload_project:
  stage: release
  when: manual
  script:
  - bundle exec fastlane release
  tags:
  - Xcode11
