stages:
  - test

test_project:
  stage: test
  script:
  - xcodebuild test -configuration Debug -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8,OS=latest' -scheme TempConverter  
  tags:
  - Xcode11
