default_platform(:ios)

platform :ios do
  desc "Run our tests"
  lane :test do
    run_tests # SCAN
  end

  desc "Sync our code signing"
  lane :signing do
      sync_code_signing # match

      mapping = Actions.lane_context[
        SharedValues::MATCH_PROVISIONING_PROFILE_MAPPING
      ]
      update_code_signing_settings(
        profile_name: mapping[ENV['MATCH_APP_IDENTIFIER']]
      )

  end

  desc "Build our App"
  lane :build do
    signing
    build_ios_app #gym
  end

  desc "Release our app"
  lane :release do
    build
    upload_to_app_store #deliver
  end

end

